const Game = {
  lastTimestamp: 0,
  dt: 0,
  gameTime: 0,
  fps: 0,
  dpr: 1,
  canvas: null,
  ctx: null,
  debugText: [],
  debugToggles: {},
  mousePos: null,
  prevMousePos: null,
  mouseVel: null,
  inputs: {},
  inputsClicked: {},
  inputsReleased: {},
  keybinds: {},
  keybindsClicked: {},
  keybindsReleased: {},
  loadProgress: 0,
  loadingText: '',
  spritesheets: {},
  fonts: {},
  state: 'main_menu',
  percentage: 0,
  finalPercentage: 0,
}
