
var Game = {
  /** @type {HTMLCanvasElement} */
  canvas: null,
  /** @type {CanvasRenderingContext2D} */
  ctx: null,
  lastTimestamp: 0,
  dt: 0,
  fps: 0,
  recentFps: [],
  avgFps: 0,
  recentFrameTimes: [],
  minFrameTime: 0,
  maxFrameTime: 0,
  avgFrameTime: 0,
  dpr: 1,
  gameTime: 0,
  debugText: [],
  inputs: {},
  inputsClicked: {},
  inputsReleased: {},
  keybinds: {},
  keybindsClicked: {},
  keybindsReleased: {},
  mousePos: null,
  prevMousePos: null,
  loading: null,
  loadingText: "",
  textures: {},
  fonts: {},
  debugToggles: [],
  ignoreNextDebugToggle: false,
  cam: {zoom:2, pos:new Vec2(0,0)},
};
