const Game = {
  id: 'topdown',
  lastTimestamp: 0,
  dt: 0,
  gameTime: 0,
  fps: 0,
  dpr: 1,
  canvas: null,
  ctx: null,
  debugText: [],
  mousePos: null,
  prevMousePos: null,
  mouseGamePos: null,
  prevMouseGamePos: null,
  mouseVel: null,
  mouseGameVel: null,
  inputs: {},
  inputsClicked: {},
  inputsReleased: {},
  keybinds: {},
  keybindsClicked: {},
  keybindsReleased: {},
  debugToggles: {},
  ignoreNextDebugToggle: false,
  loadProgress: 0,
  loadingText: '',
  cam: { zoom:3, pos:new Vec2(0) },
  defaultZoom: 3,
  spritesheets: {},
  fonts: {},
  state: 'main_menu',
}